### ISSUE TITLE
Presentatie 1 — 27/03

### ISSUE THREAD

**Issue by jonasdenil** [AntonLecock/Bachelorproef#1]
## Presentatie 1 — 27/03
1. **Werktitel bacheloproef**
2. **Beknopte omschrijving bachelorproef**
3. **Probleemstelling en/of concept van de bachelorproef**  
   (formuleer hoe je bachelorproef zich situeert binnen de sterkte van je eigen praktijk, van waar de vraagstelling en/of de uitgangspunten komen en wat je bachelorproef voor je praktijk zou moeten betekenen)
4. **Situering van de bachelorproef binnen de eigen praktijk**  
   (formuleer hoe je bachelorproef zich situeert binnen de sterkte van je eigen praktijk, van waar de vraagstelling en/of de uitgangspunten komen en wat je bachelorproef voor je praktijk zou moeten betekenen)
5. **Situering van het project binnen het werkveld**  
   (formuleer hoe je bachelorproef zich situeert binnen je werkveld. Ken je verwante creaties? Wat zijn inspiratiebronnen? Hoe zou je bachelorproef zich hiervan onderscheiden?)
6. **Retro-planning [+werkmethodes]**  
   (beschrijf hier het proces en de werkmethodes die je wenst te hanteren binnen een strikte timing, voor het tot stand komen van je bachelorproef)

**Comment by jonasdenil** [comment]
### 3. Probleemstelling en concept

De scheur, veroorzaakt door de spoorweg, tussen de stad Leuven en Kessel-Lo. Kessel-Lo, wat ook deel uit moet maken van diezelfde stad. Op vlak van:  
- **mobiliteit:** alle verkeer moet OF langs de Tiensepoort OF langs het Artoisplein. Fietsers zijn genoodzaakt om vrijwel dezelfde weg te nemen, alleen rest hun de mogelijkheid om onder het Station door te reizen. 
  Dit wanneer er meer en meer druk komt op deze belangrijke invalswegen doordat Leuven steeds meer uitbreidt. 
  Het huidige scenario zorgt er ook voor dat het centrum er voor de bewoner van Kessel-Lo als eens als "veraf" beschouwd wordt. De oplossing maakt het voor de bewoner ook al eens aantrekkelijker om de auto aan de kant te laten staan. 
- **duurzaamheid:** Er wordt kostbare oppervlakte verspild wanneer hier net nood aan is. Ook kan men op deze plekken het tekort aan begroeiing binnen de stad gaan compenseren.
- **sociaal:** Er is nood aan een ruimte waar mensen, zowel de jeugd die erg talrijk aanwezig is in Leuven (denk aan studenten) als buurtbewoners, zich kunnen ontspannen. Er kan een stress weggehaald worden uit de stad door drukte te verspreiden, terwijl de stad net hechter geheel wordt dankzij de verbinding tussen het centrum en de woonwijken achter het station.

**Comment by jonasdenil** [comment]
### 5. Situering van het project binnen het werkveld—best practices

Aan wat is er nood op deze locatie, wat kunnen we verwezenlijken op die plek? 
- **Ringland** als inspiratiebron, maar eveneens de **vernieuwing van de Leuvense Vaartkom** waar oude industrie vervangen/vernieuwd wordt tot een nieuwe stedelijke ruimte. _Een stad, complementair aan de bestaande stad._  
- **Leuven Klimaatneutraal 2030,** eveneens een ambitieus project waarbij de stad Leuven binnen 15 jaar volledig klimaatneutraal hoopt te zijn.
- **Lyon Confluence (Frankrijk), Quartier Ecoparc in Neuchâtel (Zwitserland), HafenCity in Hamburg (Duitsland)** zijn voorbeelden van hoe in onze buurlanden wordt omgegaan met het verstedelijken en terug op de kaart zetten van industriegebied binnen een stad. 
- **Park Belle-Vue** is een bestaand plan dat momenteel ten uitvoer wordt gebracht, maar benut totaal niet zijn volledige capaciteit van wat het zou kunnen betekenen voor de stad Leuven.
- **Sagrera International Park in Barcelona (Spanje)** is een prachtig voorbeeld van wat er gedaan kan worden met een spooromgeving—momenteel nog als plan, maar binnenkort een realiteit—het gevolg van een bundeling van spoorwegen in de binnenstad, ondergronds.
- **Highline in New York City (USA)** opnieuw een mooi voorbeeld van wat er gedaan kan worden met bestaande architectuur die niet meer gebruikt wordt. Zelfs in een van de drukste steden ter wereld is er een oase van rust te vinden, dit voor de zwakke weggebruikers. Ook is dit een mooi voorbeeld van een soort tweede laag bovenop de bestaande infrastructuur.
- **Estaciòn de Logroño (Spanje)** is een niet al te druk station, vergelijkbaar met Leuven. Opnieuw wordt er gebruik gemaakt van een gelaagdheid—sporen onder de grond, leefbare omgeving bovenaan.

Het feit dat wij verschillende vlakken (maatschappelijk, duurzaamheid, mobiliteit) proberen te combineren zonder een echte voorkennis, kan ons een voordeel bieden om een al dan niet utopisch beeld van de toekomst te schetsen. Wij kijken misschien op een andere manier naar data, en kunnen, zelfs wanneer ons plan niet realiseerbaar lijkt op korte termijn is het uiteraard een boeiende oefening die in andere situaties van belang kan zijn.

**Comment by jonasdenil** [comment]
### 4. Situering van de bachelorproef binnen de eigen praktijk

Wat kunnen wij als grafisch ontwerpers bijdragen aan dit probleem/deze vraagstelling?
- We houden ons niet bezig met het ingenieursaspect van deze problemen, maar focussen ons meer op het vormgeven van het probleem en/of zijn oplossing
- Onze uitgangspunten zijn gebaseerd op de data die we voor handen hebben, waar we naar op zoek zijn gegaan, maar ook op onze persoonlijke ervaring met deze problemen (aangezien we ermee in aanraking komen)

**Comment by jonasdenil** [comment]
### 1. Werktitel
- Scheur
- Spoorland
- Spoor Oase 
- Geul
- Rivier  
  - 1 rivier, 2 oevergemeenten > een metafoor die vaak gebruikt wordt
- 80 000 / Tachtigduizend
- 8ha
- IJzer
  - IJzeren Geul
  -

**Comment by AntonLecock** [comment]
### 2. Beknopte omschrijving

Alle spoorwegen in en rond Leuven werden verwezenlijkt in de 19e eeuw. Sindsdien ontstond er een tweede deel, "achter" Leuven: Kessel-Lo. Zeer lang vormden zij twee aparte werelden, dankzij de brede geul tussen hen in, de spoorweg. Deze ijzeren rivier vormt vandaag de dag nog steeds een obstakel, niet in het minst op het vlak van mobiliteit, maar eveneens op sociaal en economisch vlak. Sinds de jaren negentig is men begonnen met een ruimtelijk ontwikkelingsplan voor de stationsomgeving. Verschillende projecten werden gerealiseerd, maar nog steeds bestaat er een problematiek. Leuven en Kessel-Lo zijn verbonden, maar slechts via een overdrukke Tiense- en Diestsesteenweg. Maar meer dan ooit snakt de Leuvenaar naar een plaats van rust en ruimte: het huidige plan volstaat niet en men kan veel meer bereiken. Een oppervlakte van 8ha die te vinden is in de geul.

**Comment by jonasdenil** [comment]
### 6. Dingen te doen
- **Data vergaren**
  - Verkeerspassage
  - Exacte(re) metingen zoeken (op plannen)
  - Ruimtelijk ontwikkelingsplan van de Leuvense stationsomgeving
  - Doelen zoeken voor wat met te gewonnen oppervlakte te doen
    - stad Leuven
    - inwoners Leuven
    - Begroeiing
- **Meer research**
  - Met BUUR (Bureau Urbanisme) gaan praten
    - Hoe pakken zij dit soort projecten aan?
  - Andere best practices gaan opzoeken
- **Data gaan visualiseren & communiceren**
  - Huisstijl ontwikkelen, blijvend evolueren
  - Zoeken op welke manier zich dit het best loont
  - Platform voor data-stockage & bevindingen en dit onderhouden
1. Data vergaren 
2. Research
3. "Uitwerking" en presenteren van bevindingen

Volgende week gaan doen?

**Comment by AntonLecock** [comment]
### Wireframe presentatie 1
1. Foto van schporen + 8ha erop
2. Beknopte omschrijving > Urbanisatie
   - Op basis van empirisch materiaal, gegevens en feiten, ontwikkel je visualisaties die:
     - Licht werpen op de huidige problemen van de verstedelijking
     - mogelijke strategieën aangeven in de aanpak van deze problemen
     - en voorzover dit kan worden onderscheiden, geavanceerde concepten voorstellen
   - presentatie moet verder gaan dan alleen een representatie van de feiten
     3.

Urbanisatie is een verschuiving van de bevolking, dat zich stelselmatig van het platteland naar de stad verhuist. Dit is een huidige trend die zich zeker sinds de industriële revolutie volstrekt. Meer dan de helft van alle mensen woont nu in een stad.
(toon kaartje)
Samen met deze verschuiving van de bevolking kwamen er ook nieuwe transportmogelijkheden zoals onder meer "de IJzeren weg", de spoorweg. In Leuven werd de bouw van de spoorweg vervolledigd in 1837, sindsdien ontstond aan de overkant Kessel-Lo, de arbeidersstad. Deze stad werd als het ware afgesneden van de universiteits- en burgerstad: Leuven, door de IJzeren weg. De spoorweg bemoeilijkt de mobiliteit van en naar Leuven al sedert den beginne maar de laatste 20 jaar besloot Leuven eindelijk iets te doen aan dit letterlijk 'eeuwig' aanslepende probleem.  
Niet genoeg vonden

**Comment by jonasdenil** [comment]
### Onze visie
- Verloren ruimte door de spoorweg en zijn wissels gebruiken door deze te overkappen > de spoorweg ligt lager dan zijn 2 oevers = gunstig
  - een oppervlakte van 80 000 vierkante meter (8ha) kan worden gewonnen
  - kostbare plaatswinning voor het plaatsen van begroeiing (waar tekort van is in Leuven)
  - plaats voor een rustgevende plek > hangplek
  - verbeteren van de mobiliteit > 2 invalswegen liggen 2 tot 3km uit elkaar
  - Belle Vue park is een magere voorstelling van iets wat veel groter kon zijn
- Verschillen met bestaande stations: 
  - Antwerpen-Centraal > spoor ligt hoger en straten lopen er onderdoor
  - Leuven > spoor ligt lager waardoor het letterlijk een scheur vormt tussen Leuven en Kessel-Lo
- Het is deel van ons plan om op zoek te gaan naar een doelpubliek en ons uitresultaat gaat afhangen van dit publiek
- Soort website/platform waar wij onze opvattingen & oplossingen op kunnen "dumpen"
- Bestaand plan dat Kessel-Lo en Leuven meer een geheel gaan vormen
