### ISSUE TITLE
Presentatie 2 — 03/04

### ISSUE THREAD

**Issue by jonasdenil** [AntonLecock/Bachelorproef#3]

**Comment by jonasdenil** [comment]
### Notities presentatie 1

Gaan kijken naar wat de spoorweg als impact heeft op een stad, met als voorbeeld Brussel. 
Presentatie gaan omkeren, onderzoek hiernaar gaan doen en dan **8ha** als casevoorbeeld gaan gebruiken
- Gaan kijken naar welke communicatiemiddelen architecten enz gebruiken
  soort platform ontwerpen waar mensen beter met elkaar gaan communiceren
- In Leuven bijvoorbeeld zijn er 3 bouwmeesters waar voor de rest iedereen kan bouwen wat hij/zij wil
- Te weinig communicatie tussen deze aannemers+stad en de bevolking
- S-netwerk Brussel (Noord-Zuid verbinding: brussel naar de klote)

Boek over de spoorwegen [andere voorbeelden van hoe een spoorweg een stad verandert] — heel degelijk onder handen nemen, samenvattende cases maken (1 slide per case?) over de andere steden:
- Aarschot
- Sint-Truiden
- Tienen
- Roosendaal
- ...

**Comment by AntonLecock** [comment]
Stad Leuven contacteren:
- Geplande groei (inwoners) van zowel binnenstad Leuven als Kessel-Lo
  - Zijn hier cijfers over te vinden?
  - Kan het stijgende bevolkingsaantal gedragen worden door de huidige infrastructuur?
  - Kunnen de invalswegen (steenwegen) deze groei dragen?
- Bestaande plan/data opvragen van het ruimtelijk ontwikkelingsplan voor de stationsomgeving
- ...

BUUR contacteren:
- Wat doen zij, hoe beschouwen zij een situatie en hoe pakken zij "vernieuwing" aan?
- Doen zij zelf onderzoek, goede bronnen enz..?
- ...

Informatie zoeken rondom:
- Antwerpen (linker- rechteroever)
- ...

**Comment by AntonLecock** [comment]
![Planning Park Belle Vue](https://cloud.githubusercontent.com/assets/8662026/6929753/a344ab24-d7fd-11e4-884a-ea87f815c536.png)  
Wat kunnen we hier van terug te vinden en wie moeten we hiervoor contacteren?

**Comment by AntonLecock** [comment]
Inhoud presentatie 2 —
- Startslide
- Korte recap van presentatie 1, heel kort (2 à 3 slides)
- Evolutie van abstracts naar huidige idee (3 à 4 slides)
  1. Dit project heeft als doel een onderzoek te voeren naar de impact van de vroegere spoorwegenaanleg binnen de huidige context van verstedelijking. Het doel van het project is een brug te vormen tussen enerzijds de stad en zijn investeerders en anderzijds zijn bewoners door middel van een open source platform, met als case de stationsbuurt van Leuven.
  2. Dit project heeft als doel een onderzoek te voeren naar de mate waarin een online toegankelijk platform kan werken als een geschikt inspraak- en communicatiemiddel tussen burgers, overheden en investeerders in openbare (infrastructuur) werken, met als case de stationsbuurt van Leuven.
  3. Dit project heeft als doel een onderzoek te voeren naar een mogelijk communicatiemodel. Als graphic & information designers kunnen wij een beeldtaal ontwikkelen die de communicatie tussen de verschillende belangengroepen kan vereenvoudigen en vooruithelpen.
- Huidige idee uit de doeken doen 
  - Penta Helix Model
  - ...
