### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by jonasdenil** [AntonLecock/Bachelorproef#4]
- [x] Mailen Adrian  
- [x] Mailen naar CUO  
- [x] Mailen naar Liesbeth  
  liesbeth.huybrechts@arts.kuleuven.be  
- [x] Mailen stad (na 20 april)
- [x] Mailen naar OBK
  - [x] Vragen Toon naar locatie 
  - [x] Uitnodigen rest van OBK
  - [x] Plaats fixen
  - [x] Moment fixen

**Comment by AntonLecock** [comment]
* Succesvol inspraak organiseren kan enkel vanuit een duidelijke en onderbouwde visie op een participatief beleid;  
* De schaal van de ingreep die voorligt, bepaalt mee de betrokkenheid van de inwoners; het moet uitdagend zijn;  
* Inspraak in een vroeg stadium van het beslissingsproces, vergroot de kans op succes en tevredenheid;  
* Politici moeten een eigen visie op het probleem durven verdedigen en hierrond de dialoog aan gaan;  
* Goede communicatie over de opvolging van het inspraaktraject is belangrijk.    
Meer inspraak. (n.d.). Geraadpleegd op 7 April, 2015, van http://www.buurtcomiteskessello.be/meer-inspraak.html

**Comment by AntonLecock** [comment]
:nail_care: 

Hallo allen!

Even kort voorstellen: Jonas en ik zijn beiden student Grafisch Ontwerp en Information Design aan Sint-Lukas Brussel. We zijn momenteel hard aan het werk om ons bachelorproject tot een goed einde te brengen.

Ons project heeft als doel een onderzoek te voeren naar de communicatie tussen belanghebbenden (stakeholders) wanneer het gaat over stadsvernieuwingen. Er zijn verschillende groepen: academici, buurtbewoners (jullie), de publieke sector, investeerders, bedrijven. Met dit onderzoek kunnen wij als graphic & information designers misschien een beeldtaal ontwikkelen die toekomstige communicatie tussen de verschillende belangengroepen kan vereenvoudigen en vooruithelpen. 

Jullie zijn allemaal leden (dat vermoeden wij toch) van het Overleg Buurtcomité's Kessel-Lo, en via Toon Van Den Brempt kwamen we bij jullie e-mailadressen terecht. Wij zouden graag in gesprek gaan met jullie samen, om eens met zijn allen de communicatiemodellen tussen buurtbewoners, stad, enz. te benaderen. 

Het liefst zouden wij willen afspreken tussen 20 en 30 april. Hier volgt een link naar een doodle die we hebben opgesteld: http://doodle.com/h9c3gwiu64y89f36#table . Het zou ons project goed vooruit kunnen helpen moesten jullie er bij kunnen zijn. Hoe meer input hoe beter!

De locatie zouden we later kunnen bepalen, wanneer we een duidelijker beeld hebben van met hoevelen en wanneer we precies afspreken.

Anton & Jonas

**Comment by jonasdenil** [comment]
:shit:
