### ISSUE TITLE
Paasvakantie To Do

### ISSUE THREAD

**Issue by jonasdenil** [AntonLecock/Bachelorproef#5]
#### @jonasdenil
- Artikels lezen en belangrijke dingen aanduiden
- 
#### @AntonLecock
- Interview Adrian uittypen
- Contacten zoeken van de stakeholders
- Contact opnemen (en evt. afspraak maken) met stakeholders.
-

**Comment by AntonLecock** [comment]
#### Aan: Dienst Communicatie Stadsvernieuwing Leuven

_infohuis@leuven.be_

Beste  

Ik ben Anton Lecock, en woon al mijn hele leven in Leuven. Ik ben momenteel bezig met het afronden van mijn bachelor Grafisch Ontwerp aan LUCA School of Arts, campus Sint-Lukas Brussel. Maar natuurlijk is er nog een eindproef, waarvoor ik samenwerk met een medestudent, Jonas Denil. Hij komt ook uit het Leuvense.  

Ons project heeft als doel een onderzoek te voeren naar de communicatie tussen belanghebbenden (stakeholders) wanneer het gaat over stadsvernieuwingen. Er zijn verschillende groepen: academici, buurtbewoners, de publieke sector, investeerders, bedrijven. **Deels in samenwerking met BUUR, Bureau Urbanisme,** kunnen wij als graphic & information designers onderzoek voeren en een beeldtaal ontwikkelen die toekomstige communicatie tussen de verschillende belangengroepen kan vereenvoudigen en vooruithelpen.  

Hiervoor hebben we uiteraard hulp nodig! Jonas en ik zouden graag in gesprek gaan met zoveel mogelijk mensen die te maken hebben met stadsvernieuwingsprojecten in het Leuvense, in het verleden, nu, of in de toekomst. We willen een klaar en duidelijk beeld hebben van hoe de communicatie tussen de stakeholders er aan toegaat, voor we hiermee zelf aan de slag kunnen gaan.  

Vooral het vernieuwingsproject van het "Park Belle-Vue" zouden we willen gebruiken als casus voor ons project. Enerzijds willen we kijken hoe de communicatie verliep, langs welke kanalen, wie er sprak met wie, maar ook welke stappen er genomen werden om communicatie vooruit te helpen, enz.  

We merken op dat communicatie van gemeente naar buurtbewoners (en omgekeerd) moeilijk kan zijn en voor frustraties kan zorgen (http://www.buurtcomiteskessello.be/meer-inspraak.html). Aangezien jullie het aanspreekpunt zijn van de stad Leuven omtrent stadsvernieuwingen, zouden wij graag een afspraak willen maken met jullie—en dit omdat we uiteraard van alle belangengroepen willen horen. Is het mogelijk dat wij met jullie een gesprek kunnen hebben over ons project? Wij kijken er alvast naar uit!  

Hartelijk bedankt en met vriendelijke groeten,  

Anton Lecock
Jonas Denil  

///////

Anton: 0495 18 34 98 — anton.lecock@student.luca-arts.be 
Jonas: 0472 86 74 56 — jonas.denil@student.luca-arts.be

**Comment by AntonLecock** [comment]
#### Aan: Dienst Communicatie Stadsvernieuwing Leuven

_info@buurtcommiteskessello.be_

Beste  

Ik ben Anton Lecock, en woon al mijn hele leven in Kessel-Lo. Ik ben momenteel bezig met het afronden van mijn bachelor Grafisch Ontwerp aan LUCA School of Arts, campus Sint-Lukas Brussel. Maar natuurlijk is er nog een eindproef, waarvoor ik samenwerk met een medestudent, Jonas Denil. Hij komt ook uit het Leuvense.  

Ons project heeft als doel een onderzoek te voeren naar de communicatie tussen belanghebbenden (stakeholders) wanneer het gaat over stadsvernieuwingen. Er zijn verschillende groepen: academici, buurtbewoners (jullie), de publieke sector, investeerders, bedrijven. **Deels in samenwerking met BUUR, Bureau Urbanisme,** kunnen wij als graphic & information designers onderzoek voeren en een beeldtaal ontwikkelen die toekomstige communicatie tussen de verschillende belangengroepen kan vereenvoudigen en vooruithelpen.  

Hiervoor hebben we uiteraard hulp nodig! Jonas en ik zouden graag in gesprek gaan met zoveel mogelijk mensen die te maken hebben met stadsvernieuwingsprojecten in het Leuvense, in het verleden, nu, of in de toekomst. We willen een klaar en duidelijk beeld hebben van hoe de communicatie tussen de stakeholders er aan toegaat, voor we hiermee zelf aan de slag kunnen gaan.  

Op jullie website halen jullie enkele belangrijke punten aan omtrent de (beperkte) inspraak van buurtbewoners bij openbare werken en stadsvernieuwingsprojecten. Communicatie van en naar de stad kan moeilijk verlopen en zorgen voor frustratie. Aangezien jullie een overkoepelende organisatie zijn in Kessel-Lo en duidelijke standpunten innemen omtrent deze (mis)communicatie, zouden we graag met jullie willen praten. Is dit mogelijk? Wij kijken er alvast naar uit. 

Hartelijk bedankt en met vriendelijke groeten,  

Anton Lecock
Jonas Denil  

///////

Anton: 0495 18 34 98 — anton.lecock@student.luca-arts.be 
Jonas: 0472 86 74 56 — jonas.denil@student.luca-arts.be
