### ISSUE TITLE
To Do: Dinsdag 28/4

### ISSUE THREAD

**Issue by jonasdenil** [AntonLecock/Bachelorproef#6]
- [x] Praten met Stad Leuven (zie vragen Toon [hier](https://github.com/AntonLecock/Bachelorproef/blob/master/Research/Audiomateriaal/Toon%20Van%20den%20Brempt/Toon%20Van%20den%20Brempt%20Notities.md))  
  - [x] Transcript
- [x] Besluit vormen: **Wat** gaan we nu uiteindelijk doen/verwezenlijken?  
- [x] Adrian een mail terugsturen (transcript sturen ook)

**Comment by jonasdenil** [comment]
@AntonLecock: Issue over OBK mailen enz is closed! Hier even een opsomming wat te doen morgen!

**Comment by AntonLecock** [comment]
#### Top!
