### ISSUE TITLE
Presentatie 29/04

### ISSUE THREAD

**Issue by jonasdenil** [AntonLecock/Bachelorproef#8]
#### Focus
- **Gesprekken** gevoerd met verschillende betrokken partijen bij stadsverwezenlijkingen  
  - Adrian Vickery Hill, BUUR (Bureau Urbanisme)  
  - Toon Van den Brempt, Overleg Buurtcomité's Kessel-Lo  
  - Geert Antonissen, Infohuis (Stad Leuven)  
- Ons concept is voornamelijk gebaseerd uit de bevindingen die we opdeden **tijdens deze gesprekken** 
- **Stad** evolueert rond een **structuurplan** 
  - Hardware voor de stad, het onderliggende fundament, vormt de kern van het beleid. 
  - Vernieuwingsprojecten worden uitgevoerd in het kader van dit plan.
  - Het vorige plan, ter illustratie, was zo'n 800 pagina's lang. Geen kat die weet dat het bestaat, niemand die er iets mee doet.  
  - Ze willen zelf de bevolking meer betrekken bij dit soort projecten, maar er is niet voldoende kennis, er wordt geen initiatief genomen, en het nodige budget ontbreekt.
- **instant** moet er participatie zijn met de bevolking  
  - De huidige technologie laat dit toe!  
    - **tweerichtingsverkeer**  
  - moderator = de stad
  - wordt geleid/gestuurd (of gemodereerd), maar bestaat dankzij input (ideeën) van inwoners  
    - van in het begin **openheid van de stad uit**
#### Concept
- Via een **online** platform in de vorm van een website  
  - hier wordt het structuurplan voor de komende 20 jaar ontwikkeld = groot brainstorm-platform  
    - **tweerichtingsverkeer**  
  - het kanaliseert en centraliseert alle inbreng, en brengt het aan bij de juiste doelgroep.  
  - tool wordt aangereikt om dit participatieproces van in het prille begin te starten
  - motiveert actief deelnemen  
#### Functies

**Hoofdfuncties**  
- Als **bewoner**  
  - **Bekijken en beoordelen** van projecten van de stad en ideeën van andere bewoners  
  - **Schrijven van ideeën** of op poten zetten van projecten (dit zal echter meestal de stad zijn)  
- Als **Stad**  
  - **Naar buiten brengen** van het structuurplan door middel van verschillende projecten visueel weer te geven in plaats van een tekst van 800 pagina's 
  - **Modereren en selecteren** uit de toegeleverde ideeën van de bewoners. 
  - **Participatie** met bewoners via dit kanaal (ook informatie uitwisseling?)  
- Info moet gekanaliseerd worden zodat belangrijke info de Stad bereikt  
  - Bos moet door de bomen nog zichtbaar blijven  
- 500px werkt met **Pulse**: berekent hoe belangrijk een project/idee is volgens views, waardering, ...  
- Werken met GitHub's **push & pull** werking  
  - Wanneer iemand een project/idee uitwerkt, kan iemand dat idee aanpassen en die aanpassingen "pushen" zodat de schrijver deze ideeën kan doorvoeren  
- Soort van **waarderingssysteem** 
  - Zoals _liken_ op facebook & instagram, _sterren geven_ in de AppStore, ...  
- Google maps integratie  
  - Projecten/ideeën kunnen lokaal worden aangeduid  
  - Men kan zoeken op locatie (details, details, ...)  
- Stad moet en **simpele** approval/disapproval knop hebben
  - hierdoor moet communicatie ook makkelijker en sneller verlopen  
  - à la 'geef een beschrijving voor de commit' bij GitHub  
  - bv: **Approved** omdat: ...  
- Projecten moeten zeer **visueel** zijn, **makkelijk te begrijpen, duidelijk**  
  - niet te droog, niet te schriftelijk  
- Projecten moeten ergens gelimiteerd worden wat betreft tekst (niet te veel input)  
- Projecten worden gekanaliseerd: à la fora (categoriëen, ...)  
#### Info kanaliseren
- Info moet gekanaliseerd worden zodat belangrijke info de Stad bereikt  
  - Bos moet door de bomen nog zichtbaar blijven  
- 500px werkt met **Pulse**: berekent hoe belangrijk een project/idee is volgens views, waardering, ...  
- Werken met GitHub's **push & pull** werking  
  - Wanneer iemand een project/idee uitwerkt, kan iemand dat idee aanpassen en die aanpassingen "pushen" zodat de schrijver deze ideeën kan doorvoeren  
- Soort van **waarderingssysteem** 
  - Zoals _liken_ op facebook & instagram, _sterren geven_ in de AppStore, ...  
#### User Interface (ideeën)
- **Editor**, waar projecten uitgeschreven worden  
  - Met **zo weinig mogelijk tools** moet de gebruiker zijn project/idee zo duidelijk mogelijk maken  
  - Tekst, foto's en kaarten kunnen toegevoegd worden  
  - Bold, italic & underline tekst  
- Zeer **minimalistisch en duidelijk**, informatie & projecten moeten primeren 
- Beperkt in aantal woorden (600? 800?), met duidelijkheid en to-the-point komen tot doel 
- Ergens een onderscheid tussen de **featured projecten** met de hoogste _pulse_ en een luik waar andere projecten ook gevonden kunnen worden (zoekfunctie/sorteerfunctie/...)
#### Best practises
- VSCOcam Journal Editor  
- 500px Pulse concept  
- Medium.com Editor  
- GitHub Push & Pull concept  
- Steam Workshop concept

**Comment by AntonLecock** [comment]
Toon: "Ik denk dat ge dan ook als, u moet ontpoppen als—niet alleen als grafici, maar ook als informatiedeskundigen of mensen die daar over nadenken. En dan zou ge kunnen zeggen in uw presentatie of in uw eindwerk—of wat dan ook—van: "Kijk, wij doen pogingen om hier een tool te ontwikkelen, maar wij zijn, na onze—of tijdens onze rondvragen en contacten met allerlei stakeholders tot het besef gekomen dat zolang de overheid in kwestie, of de overheden in kwestie níet die lijn willen bewandelen van participatie—en tussentijds overleg, en luisterbereidheid, en respons, en openheid—dan zal gelijk welke tool niet helpen. Ge kunt de schoonste Mozaïek maken dat ge wilt en die overal gaan in bussen steken. Als dat eenrichtingsverkeer is—"

**Comment by AntonLecock** [comment]
Anton: Yes. That's sort of our point of view: that the community can add something more to certain projects. 
Adrian: So in what situations can they add, and what can they do? You have two approaches for dealing with the community. One is where you have... The first one is what I call the "band-aid" solution. The band-aid solution is where you basically are putting out fires, avoiding trouble. And that's where you're giving people just enough information to...
Anton: To keep them happy?
Adrian: Keep them happy, and then you can get along with what you're doing. Because in the long term, your assessment of the situation is that people are going to be angry because there's going to be change. It doesn't matter what it is, they're going to be angry. And so you basically have to make sure that they have enough information.

**Comment by jonasdenil** [comment]
https://github.com/AntonLecock/Bachelorproef/blob/master/Presentaties/Presentatie%2029:4/Presentatie-29:4.pdf

**Comment by AntonLecock** [comment]
Positiviteit is niet noodzakelijk "veel verkeer".

Visueel maken van "wall-of-text" is belangrijk.

**Comment by AntonLecock** [comment]
http://www.demorgen.be/opinie/burgers-kennen-niets-van-bruggen-en-tunnels-toch-a2302676/
